// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJj8Di-RgWzfbUVjEfE50ldhB7Dm9DT0',
    appId: '1:641719923537:web:3074c0ca3944cad2a6d970',
    messagingSenderId: '641719923537',
    projectId: 'depron-app',
    authDomain: 'depron-app.firebaseapp.com',
    storageBucket: 'depron-app.firebasestorage.app',
    measurementId: 'G-5CJHJCNVSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUKTb1arnol1TdnEDvEkC69RaFPV_o78',
    appId: '1:641719923537:android:9b3a72685806592aa6d970',
    messagingSenderId: '641719923537',
    projectId: 'depron-app',
    storageBucket: 'depron-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcm0emTLc5NoMvrHHWjldAOOO0svAz3Co',
    appId: '1:641719923537:ios:d90d3dc9b3969063a6d970',
    messagingSenderId: '641719923537',
    projectId: 'depron-app',
    storageBucket: 'depron-app.firebasestorage.app',
    iosBundleId: 'com.example.depronApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcm0emTLc5NoMvrHHWjldAOOO0svAz3Co',
    appId: '1:641719923537:ios:d90d3dc9b3969063a6d970',
    messagingSenderId: '641719923537',
    projectId: 'depron-app',
    storageBucket: 'depron-app.firebasestorage.app',
    iosBundleId: 'com.example.depronApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJj8Di-RgWzfbUVjEfE50ldhB7Dm9DT0',
    appId: '1:641719923537:web:7dc3119c2a7ca918a6d970',
    messagingSenderId: '641719923537',
    projectId: 'depron-app',
    authDomain: 'depron-app.firebaseapp.com',
    storageBucket: 'depron-app.firebasestorage.app',
    measurementId: 'G-PNGL5TH5JQ',
  );
}
